/* Generated By:JJTree: Do not edit this line. .\MiniSqlTreeConstants.java */

package parser;

public interface MiniSqlTreeConstants
{
  public int JJT_START = 0;
  public int JJTVOID = 1;
  public int JJT_CREATETABLE = 2;
  public int JJT_CREATEINDEX = 3;
  public int JJT_DROPTABLE = 4;
  public int JJT_DROPINDEX = 5;
  public int JJT_DESCRIBE = 6;
  public int JJT_INSERT = 7;
  public int JJT_SELECT = 8;
  public int JJT_UPDATE = 9;
  public int JJT_DELETE = 10;
  public int JJT_IDENTLIST = 11;
  public int JJT_COLUMNTYPE = 12;
  public int JJT_ORDERBY = 13;
  public int JJT_OREXPR = 14;
  public int JJT_ANDEXPR = 15;
  public int JJT_EXPRPRED = 16;
  public int JJT_EXPRVALUE = 17;


  public String[] jjtNodeName = {
    "_Start",
    "void",
    "_CreateTable",
    "_CreateIndex",
    "_DropTable",
    "_DropIndex",
    "_Describe",
    "_Insert",
    "_Select",
    "_Update",
    "_Delete",
    "_IdentList",
    "_ColumnType",
    "_OrderBy",
    "_OrExpr",
    "_AndExpr",
    "_ExprPred",
    "_ExprValue",
  };
}
