/* Generated By:JJTree&JavaCC: Do not edit this line. MiniSqlConstants.java */
package parser;

public interface MiniSqlConstants {

  int EOF = 0;
  int K_AND = 6;
  int K_BY = 7;
  int K_CREATE = 8;
  int K_DELETE = 9;
  int K_DESC = 10;
  int K_DESCRIBE = 11;
  int K_DISTINCT = 12;
  int K_DROP = 13;
  int K_EXPLAIN = 14;
  int K_HELP = 15;
  int K_FLOAT = 16;
  int K_FROM = 17;
  int K_INDEX = 18;
  int K_INSERT = 19;
  int K_INTEGER = 20;
  int K_INTO = 21;
  int K_ON = 22;
  int K_OR = 23;
  int K_ORDER = 24;
  int K_QUIT = 25;
  int K_SELECT = 26;
  int K_SET = 27;
  int K_STRING = 28;
  int K_STATS = 29;
  int K_TABLE = 30;
  int K_UPDATE = 31;
  int K_VALUES = 32;
  int K_WHERE = 33;
  int O_EQ = 34;
  int O_NEQ = 35;
  int O_GT = 36;
  int O_GTE = 37;
  int O_LT = 38;
  int O_LTE = 39;
  int O_LPAREN = 40;
  int O_RPAREN = 41;
  int O_COMMA = 42;
  int O_SEMI = 43;
  int O_STAR = 44;
  int S_INTEGER = 45;
  int DIGIT = 46;
  int S_FLOAT = 47;
  int S_IDENTIFIER = 48;
  int LETTER = 49;
  int SPECIAL_CHAR = 50;
  int S_STRING = 51;
  int LINE_COMMENT = 52;
  int MULTI_LINE_COMMENT = 53;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\f\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"AND\"",
    "\"BY\"",
    "\"CREATE\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DESCRIBE\"",
    "\"DISTINCT\"",
    "\"DROP\"",
    "\"EXPLAIN\"",
    "\"HELP\"",
    "\"FLOAT\"",
    "\"FROM\"",
    "\"INDEX\"",
    "\"INSERT\"",
    "\"INTEGER\"",
    "\"INTO\"",
    "\"ON\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"QUIT\"",
    "\"SELECT\"",
    "\"SET\"",
    "\"STRING\"",
    "\"STATS\"",
    "\"TABLE\"",
    "\"UPDATE\"",
    "\"VALUES\"",
    "\"WHERE\"",
    "\"=\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\"*\"",
    "<S_INTEGER>",
    "<DIGIT>",
    "<S_FLOAT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHAR>",
    "<S_STRING>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
  };

}
